server:
  port: 9091
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toristDB
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
     
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  application:
    name: TOURIST-REGISTRATION-APPLICATION

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/